name: 'unigap_de_proj2'
version: '1.0.0'

profile: 'unigap_de_proj2'

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  unigap_de_proj2:
    analytic:
      +materialized: table
    staging:
      +materialized: view
